### ISSUE TITLE
Elements switch always swap places

### ISSUE THREAD

**Issue by runlevelsix** [PEZ/SketchDistributor#1]
I have icons I want to distribute evenly, but every time I run Distributor to distribute horizontally, it swaps or reverses their order. I've only tried it so far with 2 or 3 icons.

It doesn't seem to matter what order I select the icons or if I do it in the artboard or in the sidebar. Is it arranging them based on their name? Or just swapping the order?

**Comment by PEZ** [comment]
It's supposed to keep the horizontal order. And it actually does that when I try. Can you share a simple Sketch doc where you are experiencing the problem? Then I'll have an easier time figuring out what is going on.

**Comment by adamdexter** [comment]
I'm having this same issue. Can't seem to figure out what the plugin is using to determine order of elements.

**Comment by PEZ** [comment]
When distributing horizontally the plugin is using the property `frame.left` to determine the initial order.

I haven't been able reproduce still. A sample Sketch document would really help in tracking this bug down.

**Comment by PEZ** [comment]
I spotted a potential source to this bug and have addressed it. Can't tell if it fixes the bug, though, because cannot reproduce. Please test the latest version of the plugin and see if it fixes things. (If you are using Sketch Toolbox, just uninstall and then install again.)

**Comment by Scott-Fischer** [comment]
I thought I was having the same issue with distributing horizontally until I figured out that it uses the layer hierarchy to determine the order. It seems to start with the bottom layer every time and then places each above layer to the right of the bottom layer. Not sure if this was intentional or not, but you may want to add some dialogue to the plugin prompt if it is.

**Comment by PEZ** [comment]
@Scott-Fischer: Thanks! That is the bug. Now I can reproduce it. And hopefully fix it too. =)
