### ISSUE TITLE
auto focus in text field

### ISSUE THREAD

**Issue by Nevu** [PEZ/SketchDistributor#12]
hello!

first: thank you for this great plug. Mybe its just a small, but nice feature-request:
I'd like to have an auto-focus in the text-flied (spacing), when do the shortcut.
This would speed-up the work-flow.

thx

**Comment by rorysmyth** [comment]
+1

**Comment by CarmelArad** [comment]
+1

**Comment by hellotherekevin** [comment]
+1

Additionally, it would be great to be able to toggle between the Vertical and Horizontal directions with a keyboard shortcut.

**Comment by rorysmyth** [comment]
Think the focus thing is a Sierra thing. All my plugins have lost their autofocus

**Comment by PEZ** [comment]
I wonder if it ever worked for this plugin. Anyway, I found a way to get it to work.

Had to try a few times, so you might be right about Sierra being an issue for many plugins, @rorysmyth .

Please update your plugins, folks!

@hellotherekevin: I'm not sure how to fix that. I'll have a look. Help me not lose the idea by filing it as an issue of it's own, please.
