### ISSUE TITLE
Distribute Again not work properly. (Horizontally => Vertically)

### ISSUE THREAD

**Issue by barmallion** [PEZ/SketchDistributor#16]
Please change for correct work "Distribute Again" option.

var onRepeat = function(context) {
    this.distributionHandler(context, "com.betterthantomorrow.sketch.distributor", "repeat", function() {
        Distributor.distribute(Distributor.dimension == 1 ? "Vertically" : "Horizontally", Distributor.spacing);
    });
}

**Comment by PEZ** [comment]
Thanks! Fix coming up in a jiffy.
