### ISSUE TITLE
Add options for distributing horizontally/vertically

### ISSUE THREAD

**Issue by AxelHammarback** [PEZ/SketchDistributor#17]
Feature suggestion in the image below. It would enable you to bind keyboard shortcuts to distribute horizontally/vertically, instead of having to use the radio buttons all the time.

![screenshot 2017-03-07 09 16 40](https://cloud.githubusercontent.com/assets/9819283/23647714/8a69a0d6-0317-11e7-988c-fa017649ac5f.png)

PS. Thanks for a great plugin! DS.

**Comment by PEZ** [comment]
Thanks for those kind words!

The latest version of the plugin works exactly as you suggest. Time to upgrade? 🤠

**Comment by AxelHammarback** [comment]
Great minds, etc. Thanks!
