### ISSUE TITLE
Request: Automatically detect Horizontal or Vertical spacing

### ISSUE THREAD

**Issue by songcarver** [PEZ/SketchDistributor#18]
I'd love if Distributer looked at the position of the selected items and guessed what I'm likely to want to do. For example, by adding up all the vertical spacing between the existing selection, and the horizontal spacing, and using the cumulative spacing as the indicator of which orientation I'll likely be wanting. 

Something like a checkbox for [√]  Vertical/Horizontal detection

**Comment by AdamSzakal** [comment]
Yeah, I was thinking the same thing! I use it to distribute things vertically 95% of the time – how about defaulting to vertical distribution, except when objects are vertically aligned with a certain margin, pixel or percentage-wise?

**Comment by songcarver** [comment]
Ah, naturally, horizontal is my most popular use case. I might try to write some code to test the idea of auto-detection.

**Comment by songcarver** [comment]
OK — I wrote something: you can play with it here, and also download code (Coffeescript)
https://framer.cloud/jVJQY

What's thoughts on centering on the non-spaced axis?

**Comment by PEZ** [comment]
Very nice demo!

I'd like to know if you guys are using the latest version of Distributor? It has a different workflow than earlier versions. It might make this feature less needed. Might. You might be using the latest version and still feel the need for this kind of behaviour. Let me know.

Back to the demo. It seems to do a bit more than just distributing, since it also aligns the objects. I like that idea, but it raises a couple of more questions in how much control we want of this alignment. Should it align along the top, center or bottom of the objects (for horizontal distribution). Left, center, right, for vertical distribution? Should the user be able to choose that somehow? I tend to lean towards that Sketch already has excellent tools for alignment, but there could be reasons to have this kind of ”tidy up smartly” feature.

**Comment by AdamSzakal** [comment]
NIce stuff, @songcarver ! I think that it might not be intuitive enough though! Just like Sketch's resize options have confused a lot of user for the smart assumptions it does behind the scenes, I think this will too. With that said – if this logic is used only to decide which of the aligning directions are chosen by default, the stakes will be low enough to not annoy the user?

@PEZ Just saw that there were shortcuts for aligning horizontally/vertically, haha! I think the shortcuts are really uncomfortable to do one-handed though, especially for aligning horizontally. I used to be able to tab between the aligning directions – and it was awesome – but I can't anymore. I've tried fiddling with the system settings but to no avail – is this something you've changed? 


Edit: Another reason not to use a direction-prediction (albeit being a cool name): the user often tries to have a mental image of what's gonna happen – if the same thing happens all the time things will probably be considered more efficient, even though it might require an extra keystroke. Using a prediction, the user always will need to evaluate if the algorithm got things right or not. 👺

**Comment by PEZ** [comment]
No, it was something that stopped working with some release of Sketch or MacOS. Partly the reason I added the shortcuts.

Distributor works with Runner though, maybe that could help your one-handed workflow?

**Comment by songcarver** [comment]
@PEZ Yeah I'm using latest greatest. I'm thinking just a checkbox for 'Guess Orientation', if enabled, would set the default radio button.

@AdamSzakal I think the Sketch resize options were just a confusing design. New UI in Sketch 44 should fix that. 

RE: Additionally performing a center alignment, that was just me wanting to clean up, so the plugin could be fine without it.

**Comment by PEZ** [comment]
@songcarver A problem with that is that it is very hard to make an interactive dialogue box with the current implementation. So selecting the right orientation in the UI when ticking that box would probably mean to switch UI framework to an HTML view. That's something I have wanted to do for a while, but anyway.
