### ISSUE TITLE
Request: Space from center

### ISSUE THREAD

**Issue by songcarver** [PEZ/SketchDistributor#19]
I'd love the ability to space a set of elements' **center** a fixed distance apart.

The workaround is to put these in equal width containers, but I'd love to remove that step.

**Comment by PEZ** [comment]
This could go as an option in the distribution settings dialogue, right?

**Comment by songcarver** [comment]
Yup, it's definitely a boolean option. 👍

**Comment by Vincz** [comment]
Hi! I added this feature in the following PR : https://github.com/PEZ/SketchDistributor/pull/27
Hope you'll enjoy it :)

**Comment by PEZ** [comment]
I pulled #27 now. Now trying  to get the new version out.

**Comment by PEZ** [comment]
Now it seems to be out there. Version 1.2.1. Please let me know if it works for you guys or not.

One thing I might want to fix is that it probably should ”remember” the combination of direction and anchor. If that makes sense. But right now if you distribute vertically between centers also next horizontal distribution will default to center-spacing.
