### ISSUE TITLE
(Solved) Not compatible with Sketch 45

### ISSUE THREAD

**Issue by Elifro** [PEZ/SketchDistributor#21]
It seems like there is a problem with the latest version of sketch. Any ideas on how to solve this?

**Comment by JensNielsen81** [comment]
Same here, the option window wont show.
Love the plugin by the way, use it all the time.

**Comment by PEZ** [comment]
Are you guys running the latest version of Distributor? Just checking, because it contains a fix for compatibility with Sketch 45.

**Comment by JensNielsen81** [comment]
I am.
I got an update today - 45 (43475) - after i installed it, Distributor stoped working.

**Comment by Elifro** [comment]
wow, didn't even check that. It works fine with version 1.1. Thanks!

**Comment by JensNielsen81** [comment]
Ahhh sorry, works now. thanks

**Comment by PEZ** [comment]
Cool. I'm am super happy it works! Let's leave this issue open a few days so that people having the issue finds it easier.

**Comment by pinakeenaik** [comment]
How does one check distributor's version?

**Comment by PEZ** [comment]
@pinakeenaik, In Sketch: **Plugins -> Manage Plugins…**

Latest version is `1.1` and once you have upgraded to that you will be able to do future upgrades via the **Manage Plugins…** dialog (that's a new feature in Sketch 45 which Distributor 1.1 supports).

**Comment by pinakeenaik** [comment]
@PEZ Thank you! Super helpful!

**Comment by irfanpawoon** [comment]
what do you mean by 1.1? it still doesn't work for me, i am using Sketch 4.51

**Comment by irfanpawoon** [comment]
oh got it, now it works!

**Comment by benzai** [comment]
Just updated the plugin to 1.1 and I can confirm it works (again) in Sketch 45. Huge thanks!!
