### ISSUE TITLE
Use arrow keys to change Spacing input (and skip by 10 with Shift+Up/Down)

### ISSUE THREAD

**Issue by damenleeturks** [PEZ/SketchDistributor#3]
Can you do that?

**Comment by PEZ** [comment]
I'm not sure how to do it. But if I can figure it out and it is not too much work, I will definitely do it.

**Comment by damenleeturks** [comment]
Were you able to figure it out?

**Comment by PEZ** [comment]
I think I know how to do it now, but it's quite some work, I'll need to implement the UI in HTML instead to be able to catch key-down events. Maybe some day when I find a pocket of free time. =)
