### ISSUE TITLE
Feature request: distribute from layer panel position

### ISSUE THREAD

**Issue by max1mvs** [PEZ/SketchDistributor#30]
An excellent add-on to this already brilliant plugin could be the ability to distribute the layers horizontally or vertically depending upon their position in the layer panel. So for instance if I have a menu item with item A | B | C and I want to re-arrange these to C | A | B, I could re-arrange these in the layer panel so that they are hierarchically aligned like this:

C
A
B

Then distribute horizontally with spacings as today turning this option on, and they would be re-distributed on the artboard correctly. The same could go for dealing with layers vertically, so if I have an old-school left-hand menu looking like this:

Menu item A
Menu item B
Menu item C

And they are layered like this in the layer panel as well; I could easily re-arrange these by just moving them around in the layer panel, then use SketchDistributor to place them correctly for me on the artboard with proper spacing.

Thank you for an indispensable plug-in!

**Comment by PEZ** [comment]
Thanks for sharing this idea! I love it. ButI'll have to think about how hard it would be to implement it. Might be quite easy, but also might be a lot of work. :smile:

**Comment by max1mvs** [comment]
I totally understand! But I believe that would be a wonderful feature that a lot of designers could use. I would gladly help, were it not for my limited knowledge regarding this! Thank you for your great contribution with a plugin I use a lot on a daily basis! 😃👍🏻⭐️
