### ISSUE TITLE
Only works after restarting sketch

### ISSUE THREAD

**Issue by moniquep** [PEZ/SketchDistributor#7]
This is probably my most used plugin, so thank you. I though I should let you know that it generally only works if I use it as soon as I open up a project, after the project has been open for a while and I've done a fair bit of editing it stops working, i.e. an error message pops up saying no objects are selected, or I run the plugin and nothing happens. It works again after restarting sketch.

**Comment by PEZ** [comment]
Hi! It sounds like you could be using an old version of the plugin. There is a bug in Sketch 3.4.2 that trips up some plugins when the user has more than one Sketch document open (would explain why it works after restart). I uploaded a version that dodges this bug the other day. Please try updating and let me know if it helps or not. I'm all ears!
