### ISSUE TITLE
Does this work in 3.5+

### ISSUE THREAD

**Issue by shanegriffiths** [PEZ/SketchDistributor#8]
Hi, before I upgrade could someone confirm if this plugin is supported?

Many thanks

S

**Comment by PEZ** [comment]
Don't know what you mean by **supported** =) But it does work with Sketch 3.5.2 as far as I can tell.

**Comment by PEZ** [comment]
And I can confirm it works in 3.6 as well. =)

**Comment by shanegriffiths** [comment]
Hi Peter, that's great to know. Many thanks

S
